This notebook source copied from https://www.tensorflow.org/tutorials/quickstart/beginner

In [3]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [4]:
import tensorflow as tf

In [5]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 1s 0us/step


In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6878824 ,  0.19181582, -0.22656554, -0.68916696, -0.10247704,
        -0.20335254, -0.2990028 , -0.35829574, -0.24935174, -0.32093722]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.06547225, 0.15779941, 0.10384956, 0.0653882 , 0.11756975,
        0.10628842, 0.09659298, 0.09103218, 0.10150998, 0.09449734]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

2.2415988

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0637 - accuracy: 0.9801
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0567 - accuracy: 0.9811
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0515 - accuracy: 0.9836
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0469 - accuracy: 0.9849
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0433 - accuracy: 0.9859


In [14]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0714 - accuracy: 0.9803


[0.07139211148023605, 0.9803000092506409]

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.6059845e-09, 1.2560735e-12, 6.5747436e-08, 6.0254897e-05,
        8.3635078e-12, 6.4178320e-09, 3.9401605e-15, 9.9993312e-01,
        3.7676088e-08, 6.5736467e-06],
       [1.6100233e-09, 5.8351156e-07, 9.9999785e-01, 8.1950310e-07,
        7.4381828e-25, 4.9784887e-09, 5.6917644e-09, 7.4554766e-19,
        7.3206547e-07, 1.8399385e-21],
       [6.7212561e-08, 9.9939358e-01, 1.6584723e-05, 1.4097336e-06,
        2.9851817e-05, 2.2802080e-07, 4.1768390e-06, 4.8222428e-04,
        7.1948198e-05, 9.2495265e-09],
       [9.9998295e-01, 1.5429069e-11, 2.7879105e-06, 5.2296133e-07,
        1.7202314e-09, 4.7465851e-06, 3.9494980e-06, 4.0199543e-06,
        1.9804201e-09, 9.0190525e-07],
       [3.8951895e-09, 2.3295164e-12, 2.1400091e-07, 1.7014216e-10,
        9.9987209e-01, 9.9661120e-11, 8.7648324e-08, 8.1366295e-08,
        3.2368177e-08, 1.2740000e-04]], dtype=float32)>