In [46]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import tensorflow as tf
from matplotlib import pyplot as plt

In [27]:
iris = load_iris()

print(rf"iris.filename: {iris.filename}")

iris.filename: /usr/local/lib/python3.6/dist-packages/sklearn/datasets/data/iris.csv


In [28]:
iris_data = iris.data
iris_target = iris.target
iris_target_names = iris.target_names
iris_feature_names = iris.feature_names

print(rf"iris_target_names: {iris_target_names}")
print(rf"iris_target: {np.sort(np.unique(iris_target))}")

print(rf"iris_feature_names: {iris_feature_names}")
print(rf"iris_data[0]: {iris_data[0]}")

iris_target_names: ['setosa' 'versicolor' 'virginica']
iris_target: [0 1 2]
iris_feature_names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
iris_data[0]: [5.1 3.5 1.4 0.2]


In [69]:
class_count = len(iris_target_names)

In [141]:
print(rf"iris_target.dtype: {iris_target.dtype}")

iris_y = tf.keras.utils.to_categorical(y=iris_target, num_classes=class_count, dtype=iris_target.dtype)


iris_target.dtype: int64


In [144]:
print(iris_y[:10])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [145]:
seed = 0
train_data, test_data, train_label, test_label = train_test_split(iris_data, iris_y, test_size=0.3, random_state=seed)

In [146]:
print(rf"train_data[0]: {train_data[0]}")
print(rf"test_data[0]: {test_data[0]}")


train_data[0]: [5.  2.  3.5 1. ]
test_data[0]: [5.8 2.8 5.1 2.4]


In [172]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Input(4),
    tf.keras.layers.Dense(100, activation=r'relu'),
    tf.keras.layers.Dense(class_count, activation=r'softmax')
])

In [173]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
              loss=r'categorical_crossentropy',
              metrics=[r'accuracy'])

In [174]:
model.fit(train_data,
          train_label,
          batch_size=32,
          epochs=50,
          validation_data=(test_data, test_label))

Epoch 1/50
4/4 [==============================] - 0s 42ms/step - loss: 1.1252 - accuracy: 0.3714 - val_loss: 1.1525 - val_accuracy: 0.2444
Epoch 2/50
4/4 [==============================] - 0s 9ms/step - loss: 0.8544 - accuracy: 0.5905 - val_loss: 0.6694 - val_accuracy: 0.7556
Epoch 3/50
4/4 [==============================] - 0s 8ms/step - loss: 0.7557 - accuracy: 0.6381 - val_loss: 0.6034 - val_accuracy: 0.6000
Epoch 4/50
4/4 [==============================] - 0s 7ms/step - loss: 0.6244 - accuracy: 0.6952 - val_loss: 0.7257 - val_accuracy: 0.6000
Epoch 5/50
4/4 [==============================] - 0s 9ms/step - loss: 0.5296 - accuracy: 0.6952 - val_loss: 0.4498 - val_accuracy: 0.9333
Epoch 6/50
4/4 [==============================] - 0s 8ms/step - loss: 0.4854 - accuracy: 0.7619 - val_loss: 0.4121 - val_accuracy: 0.8444
Epoch 7/50
4/4 [==============================] - 0s 8ms/step - loss: 0.4253 - accuracy: 0.9048 - val_loss: 0.4803 - val_accuracy: 0.6000
Epoch 8/50
4/4 [=================

In [175]:
test_loss, test_acc = model.evaluate(test_data, test_label, verbose=2)

print('Test Loss:', test_loss)
print('Test accuracy:', test_acc)

2/2 - 0s - loss: 0.1103 - accuracy: 0.9778
Test Loss: 0.11032174527645111
Test accuracy: 0.9777777791023254


In [176]:
test_predictions = model.predict(test_data)

In [177]:
predict_index = 10

print("test_predictions[predict_index]", test_predictions[predict_index])
print("test_label[predict_index]", test_label[predict_index])

test_predictions[predict_index] [7.8702524e-06 3.8228121e-02 9.6176404e-01]
test_label[predict_index] [0 0 1]
